# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fitgram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  pod 'SwiftCSVExport'
  pod 'SteviaLayout'
  pod 'Kingfisher'
  pod 'ASPCircleChart'

  # Pods for fitgram

  target 'fitgramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fitgramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
